### ISSUE TITLE
I'm trying out your stuff

### ISSUE THREAD

**Issue by tgeorgel** [AlaaZorkane/Difys#8]
Heya, i'm trying you frameworks, that looks amazing for now.
However i think i'm lost.. 
The doc is really incomplete, i did everything that you said in the make you first plugin section, and it doesn't seems to be working :

```
(node:55866) UnhandledPromiseRejectionWarning: TypeError: Cannot set property 'domain' of undefined
    at EventEmitter.init (domain.js:428:15)
    at EventEmitter (events.js:27:21)
    at Socket (dgram.js:71:16)
```

Thanks for helping :)

**Comment by Zirpoo** [comment]
The Master branch is kinda old. Have you tried the **reviewed** branch of Difys ?
